version: '3'
services:
  api:
    build: ../src-api
    ports: 
      - 5000:5000
    environment:
      - PORT=5000
      - DB_URI=${DB_URI}
    volumes:
      - roomeditimages:/app/public/images
      - roomeditrooms:/app/public/rooms
  frontend:
    build: ../src-frontend/bootstrap/RoomEdit
    ports:
      - 80:80
    

volumes:
  roomeditimages:
  roomeditrooms: